# Font configuration
[font]
#size = 14.0 # Adjust to your liking

[font.normal]
family = "0xProto Nerd Font Mono"
# style = "Regular" # This is often not needed if the family name is correct

[font.bold]
family = "0xProto Nerd Font Mono"
style = "Bold"

[font.italic]
family = "0xProto Nerd Font Mono"
style = "Italic"

#[font.normal]
#family = "MesloLGS NF"
#family = "0x Proto Nerd Font"
